Androz2091/discord-player

README.md
src/Player.js

Throw `Error` instead of `Message` if `Player` does not have any listeners registered for the `error` event.

♻️ Throw Error instead of Message

---

package.json
src/Player.js
typings/index.d.ts

Small PR that just serves to allow for a `Track`object to be a valid query type for the main play() method. I saw that the code supported a Track object, so thought it might be a good idea to add it.
- Types updated in both `typings\index.d.ts` and inline JSDocs
- Also added `@types/node` package to prevent IDE's from yelling when editing the index.d.ts

Added Track as a valid query type for play() method

---

package.json
src/Player.js

The PR updates/fixes
- Updates `ytdl-core` to `4.2.1`
- Removes console warnings about `.shortDescription` & `thumbnail.thumbnails`
- Adds best quality possible thumbnail instead of first thumbnail

chore: bump ytdl-core and fix warnings

---

src/Player.js

This PR fixes:
- Updates `error` event doc to correct typing ([view typing](https://github.com/Androz2091/discord-player/blob/b1c9db39567ae985fbc1ed9c4ce37224d7701e6a/typings/index.d.ts#L82))

fix: fix incorrect error event docs

---

src/Player.js

fix searchResults event still fires even when firstResult is true

fix firstResult

---

src/utils/AudioFilters.ts

Mistake in `AudioFilters.names` and `AudioFilters.length`
> Temporary fix for master: `AudioFilters.length - 2`

:bug: Mistake in filters length

---

src/Player.ts

- This fixes the problem where the first track of parsed youtube playlist gets played twice;
- Changed code order so initial `trackStart` event now can see the queue;
- Added a new optional parameter to `Player#play` and `Player#_searchTracks`: `startFromIndex (number)`: 
+ This parameter lets the user priorities the track with corresponding index (array index, starts from `0`), `0` by default.
+ If one is specified and there is no queue, the specified track will be played first;
+ If it's already playing then the specified track will be put on the first index of the added playlist.
js: Tested and working [Condition used: Equivalent modified code in libs]
ts: Not yet tested.

Proposal changes based on #477

---

src/types/types.ts

Adding JSDoc for the Player#trackEnd event. I suspect this also makes it appear in the online documentation, because right now it isn't in there.

docs: add trackEnd event

---

CONTRIBUTING.md
docs/migrating/migrating.md
example/music-bot/index.js
example/music-bot/package.json
src/Player.ts
src/types/types.ts
yarn.lock

This update will cause an error to be thrown if the discord client has no `GUILD_VOICE_STATES` intent enabled.
- docs: add `trackEnd` event (#674)
- fix(Player): add intents checking (fixes issues like #673)
- chore(example): bump discord-player

fix(Player): add intents checking

---

src/Player.ts
yarn.lock

Started a local instance of https://github.com/Androz2091/discord-music-bot for my server. It sent seemingly random channels when starting a new song. Found that line probably faulty line.

fix(Player): don't change connection channel when random user joins

---

src/Player.ts

Pass the player's custom `ytdlOptions` to the `ytdlGetInfo` call made by youtube search function. This should fix the unintended behavior difference between the `search` and `play` functions, as `play` function is able to play age restricted videos in EU when a youtube `cookie` is passed as a header, but `search` function is unable to find the video.
See also: https://github.com/Androz2091/discord-player/discussions/687 (I think this is related to it)

Pass ytdlOptions for ytdlGetInfo

---

src/Structures/Queue.ts

it should fix the autoplay mode.
autoplay should never ignore a track in a queue and should be triggered when the queue is empty.
- [ Y ] These changes have been tested and formatted properly.

Fix AUTOPLAY

---

src/Player.ts

connection.channel rapidly changing in a large server with a busy voicestate, it shud never change.
fix: it shud only change the connection.channel when the bot being moved somewhere else.
also fixing how it handles voice move so it triggers channelEmpty correctly, on member move from connection.channel and bot move to an empty channel.
last thing is limiting the join and leave to the connection.channel only
- [ Y ] These changes have been tested and formatted properly.

Fix _handleVoiceState

---

README.md

this adds the [Dodong music bot](https://github.com/nizeic/Dodong) (uses discord.js v13 & discord-player@dev) to the list of example bots in the readme

add Dodong to list of example bots

---

package.json
src/Structures/Queue.ts

Adds the first element of the queue into the shuffling method. (#1284)

Shuffled first 

---

src/utils/AudioFilters.ts

Since [this commit](https://github.com/Androz2091/discord-player/commit/40f772fa5bd336818dbc0890998cf3ce72e4d1a2), custom AudioFilters were not working. This PR fixes that by removing the getter on filters.

fix filter setting

---

packages/discord-player/src/utils/QueryResolver.ts

Changed the regex variable to be able to recognize user-created apple music playlists. 
User playlists on Apple Music have `u-` appended after `pl.` in the URL. The ids also contain uppercase and lowercase characters from a-z.
tested and working properly. functions the same as a normal Apple Music playlist would.

feat(QueryResolver): apple music user playlists

---

packages/discord-player/src/Structures/GuildQueue.ts
packages/discord-player/src/Structures/GuildQueueHistory.ts

Added getSize method / size property to the GuildQueue and GuildQueueHistory to have consistency when using queue (similar to queue.isEmpty())

feat(GuildQueue): add size getter

---

packages/discord-player/package.json

This will fix **Could not find declaration file for module 'discord-player'** when using typescript with module resolution set to Node16 or NodeNext.

Fix declaration file not found

---

docs/examples/autocomplete_search.md
docs/faq/common_errors.md
docs/faq/how_to_access_player.md
examples/README.md

- Added better handling example for AutoComplete
- MasterPlayer example
- Uncommon problem fix
- Added community bot implementation link

Update docs for AutoComplete and minor changes

---

apps/website/pages/docs/guides/community-resources.md
docs/community/community_resources.md
examples/karasu/README.md

update references for karasu-music-bot

update references of 'karasu-music-bot' to 'auricle-music-bot'

---

README.md
docs/community/community_resources.md
docs/migrating/migrating.md

- Update Jappan Bot version in Community bot page
- Updated readme & migrating doc page for initializing player after `autoRegisterExtractor` being depreciated.

Update Docs to reflect autoRegisterExtractor depreciation

---

examples/karasu/yarn.lock
packages/discord-player/src/Player.ts
packages/discord-player/src/extractors/ExtractorExecutionContext.ts
packages/discord-player/src/index.ts
packages/discord-player/src/types/types.ts
packages/discord-player/src/utils/FFmpeg.ts
packages/discord-player/src/utils/FFmpegStream.ts

This custom ffmpeg stream implementation is based on prism-media's ffmpeg stream with some changes to fit discord-player's need. Users dont have to do anything, it is simply swapped out in internal code. This change also removes deprecated options from player and improves `player.scanDeps()` method.

feat: implement custom ffmpeg stream

---

docs/community/community_resources.md

Added [Wego Overseer](https://github.com/rickklaasboer/wego-overseer) to community resources.
Music commands visible [here](https://github.com/rickklaasboer/wego-overseer/tree/main/src/commands/music).

docs: add wego overseer to community resources

---

README.md
examples/karasu/yarn.lock
packages/extractor/package.json
packages/extractor/src/extractors/common/helper.ts
yarn.lock

Added yt-stream as a possible extraction engine

---

README.md
apps/website/src/pages/guide/_guides/migrating/migrating.mdx
apps/website/src/pages/guide/_guides/welcome/welcome.mdx
packages/discord-player/README.md

In the guide, you're using
```js
const channel = interaction.message.member.voice.channel;
```
to get the voice channel of the user. But when I looked in the discordjs documention, there is no `message` property for `commandInteraction`, tough there is `message` property for other interaction. But you can directly access the channel like this too, which I'm using in my music bot too
```js
const channel = interaction.member.voice.channel;
```

Fix typo for userVoiceChannel in the documention

---

packages/discord-player/src/manager/GuildQueuePlayerNode.ts
packages/discord-player/src/types/types.ts

Additional two options for played time ( leftChar ) and for unplayed time (rightChar) . As it is for the `line` it goes to ▬ when not provided

createProgressBar options

---

apps/music-bot/src/KarasuClient.ts
apps/website/src/pages/guide/_guides/extractors/set_bridge_source.mdx
apps/website/src/pages/guide/index.tsx
packages/discord-player/src/extractors/ExtractorExecutionContext.ts
packages/discord-player/src/manager/GuildNodeManager.ts
packages/discord-player/src/types/types.ts
packages/extractor/src/extractors/AppleMusicExtractor.ts
packages/extractor/src/extractors/SoundCloudExtractor.ts
packages/extractor/src/extractors/SpotifyExtractor.ts
packages/extractor/src/extractors/common/BridgeProvider.ts
packages/extractor/src/extractors/common/helper.ts
packages/extractor/src/extractors/index.ts
packages/tsconfig/base.json

TLDR; This PR introduces `BridgeProvider` which allows some extractors to conditionally stream from the specified source.
Extractors such as `SpotifyExtractor` and `AppleMusicExtractor` cannot facilitate the audio streaming functionality. Bridging is a mechanism that allows extractors such as `AppleMusicExtractor` and `SpotifyExtractor` to provide audio stream from alternative sources. The default source for this particular case has been `YouTube` for a long time and overriding this behavior has been difficult.
The `BridgeProvider` API allows overriding default bridging mechanism and enables us to pick which source shall be used. Currently, `BridgeProvider` only supports `SoundCloud` and `YouTube` as its bridging source.
A quick example on how to set up `BridgeProvider` using `SoundCloud` …

feat: introduce BridgeSource

---

apps/website/src/data/showcase.ts

Renamed my bot that I previously added to showcase. The reason is that the bot was renamed now before submitting bot verification request to Discord. The name will not change any more.

Rename bot in showcase

---

apps/website/src/data/showcase.ts
package.json
packages/extractor/package.json
packages/extractor/src/extractors/AttachmentExtractor.ts
yarn.lock

This PR adds experimental support for [mediaplex](https://github.com/androzdev/mediaplex) lib. It may not work 100% but most of the times it can populate the `duration` field of the track, which was always set to 0 for attachments and supports wide range of media format.
To enable this, we just have to install `mediaplex`.

feat(AttachmentExtractor): experimental mediaplex support

---

apps/website/src/data/showcase.ts

- Updated Cadence bot `discord-player` version to `6.6.2`.

chore: Update Cadence discord-player version

---

packages/extractor/package.json

Update spotify-url-info version from 3.2.5 to 3.2.6
When using the Spotify extractor the extractor will sporadically fail to find info about a given Track. Updating to the latest minor version fixes this. See: https://github.com/microlinkhq/spotify-url-info/issues/122#issuecomment-1656920131

chore(SpotifyExtractor): Update spotify-url-info version

---

apps/website/src/data/showcase.ts
apps/website/src/pages/guide/_guides/faq/common_errors.mdx
apps/website/src/pages/guide/_guides/faq/how_to_access_player.mdx

- [Docs] Mediaplex is a option for Opux Encoding
- [Docs] Discord Player is singleton by default
- [Docs] Dockerize for ffmpeg
- [Showcase] Updated Jappan discord-player version
- [ X] This PR includes only documentation changes, no code change.

[Docs] Mediaplex and discord-player singleton

---

apps/website/src/data/showcase.ts
packages/discord-player/src/DefaultVoiceStateHandler.ts

- Move if statement for `if (queue.hasDebugger)` that was incorrectly placed around the logic for pauseOnEmpty.

fix: solve pauseOnEmpty not working without debugger

---

README.md
packages/discord-player/__test__/serde.spec.ts
packages/discord-player/src/errors/index.ts
packages/discord-player/src/fabric/Playlist.ts
packages/discord-player/src/fabric/Track.ts
packages/discord-player/src/index.ts
packages/discord-player/src/utils/serde.ts
packages/extractor/src/extractors/common/helper.ts

This pr introduces 4 new helper functions:
- `encode()`: Produces base64 representation of serialized data
- `decode()`: Produces serialized json data from encoded string
- `serialize()`: Transforms structures such as `Track` or `Playlist` into raw json
- `deserialize()`: Produces `Track` or `Playlist` from the serialized json data
This is helpful to people who want to store tracks and playlists inside database and quickly re-initialize it.

feat: add serialization and deserialization methods

---

packages/discord-player/src/utils/serde.ts

Remove $ from `SerializedType` value since it is mapped by `$type: 'VALUE'`

fix(serde): remove $ from SerializedType value

---

apps/music-bot/package.json
apps/music-bot/src/KarasuClient.ts
apps/music-bot/src/commands/play.ts
apps/music-bot/tsconfig.json
apps/website/package.json
apps/website/src/pages/guide/_guides/faq/performance_optimization.mdx
packages/adapter-local/package.json
packages/adapter-remote/package.json
packages/core/package.json
packages/discord-player/package.json
packages/discord-player/src/Player.ts
packages/discord-player/src/VoiceInterface/StreamDispatcher.ts
packages/discord-player/src/extractors/BaseExtractor.ts
packages/discord-player/src/manager/GuildQueueAudioFilters.ts
packages/discord-player/src/manager/GuildQueuePlayerNode.ts
packages/discord-player/src/types/types.ts
packages/discord-player/src/utils/FFmpegStream.ts
packages/downloader/package.json
packages/equalizer/package.json
packages/extractor/package.json
packages/extractor/src/extractors/AppleMusicExtractor.ts
packages/extractor/src/extractors/SpotifyExtractor.ts
packages/extractor/src/extractors/YoutubeExtractor.ts
packages/extractor/src/extractors/common/helper.ts
packages/ffmpeg/package.json
packages/opus/package.json
packages/tsconfig/package.json
packages/utils/package.json
packages/voice/package.json
yarn.lock

This PR implements demuxer for `webm/opus` and `ogg/opus` streams. When such streams are available and condition does not require the use of ffmpeg, discord-player will skip ffmpeg entirely. This update does not include breaking changes. Developers currently have to pass `skipFFmpeg: true` in main player options for this to work. We may enable this by default after performing enough tests _(in production)_.
You can still use filters such as `volume controller`, `equalizer` or `biquad` while using `skipFFmpeg` without any issues. You can also use ffmpeg filters but discord-player will switch back to ffmpeg when you use ffmpeg filters or seek().
`skipFFmpeg` may not work all the time, but you should not notice any differences as a user. Currently, this only works with `YoutubeExtractor` …

feat(GuildQueuePlayerNode): implement demuxer

---

packages/discord-player/src/manager/GuildQueueAudioFilters.ts

fix(AFilterGraph): expose current biquad filter

---

apps/music-bot/src/commands/shuffle.ts
packages/discord-player/src/manager/GuildQueue.ts
packages/discord-player/src/utils/Util.ts

This mode does not mutate the queue and only shuffles before selecting next track. It can be enabled/disabled on-the-fly.
```js
// enables/disables dynamic shuffling mode
queue.toggleShuffle();
// enable
queue.enableShuffle();
// disable
queue.disableShuffle();
// enable traditional shuffle (this is a one-time process)
queue.enableShuffle(false);
queue.tracks.shuffle();
```

feat: add dynamic shuffle mode

---

packages/discord-player/src/hooks/common.ts
packages/discord-player/src/types/types.ts

Currently the hooks exported by discord-player operate on the first instance of `Player`. This PR adds a new function called `bindHook` which allows users to bind hooks to other instance of player.
```js
import { bindHook, useMainPlayer, Player } from 'discord-player'
// create player instance
const player = new Player(client, {...});
// bind hooks to 'player'
bindHook(player);
useMainPlayer() // this equals to 'player' above
```
> This by default uses first instance for compatibility reasons.

feat: add bindHook function

---

apps/music-bot/src/listeners/ready.ts
packages/discord-player/src/extractors/ExtractorExecutionContext.ts
packages/extractor/package.json
packages/extractor/src/extractors/common/BridgeProvider.ts
yarn.lock

This PR adds `options` parameter to `loadDefault` method of `ExtractorExecutionContext` which allows devs to pass extractor options in this format:
```js
await player.extractors.loadDefault(null, {
ExtractorName: {...}
});
```

feat(ExtractorExecutionContext): allow passing options via loadDefault

---

packages/discord-player/src/manager/GuildQueuePlayerNode.ts

Fixes issues such as `Cannot find opus library` with demuxable tracks when using mediaplex.

fix(GuildQueuePlayerNode): use @discord-player/opus

---

packages/extractor/src/extractors/AppleMusicExtractor.ts
packages/extractor/src/extractors/SpotifyExtractor.ts

Remove unnecessary ternary check for bridgeProvider in AppleMusicExtractor and SpotifyExtractor.
This check is not necessary because the baseExtractor already returns default bridgeProvider in case user hasn't provided any.

perf: remove unnecessary bridgeProvider check

---

apps/music-bot/src/listeners/ready.ts
packages/discord-player/src/Player.ts
packages/discord-player/src/extractors/BaseExtractor.ts
packages/discord-player/src/extractors/ExtractorExecutionContext.ts
packages/extractor/src/extractors/AppleMusicExtractor.ts
packages/extractor/src/extractors/SoundCloudExtractor.ts
packages/extractor/src/extractors/SpotifyExtractor.ts
packages/extractor/src/extractors/YoutubeExtractor.ts

This PR adds support for `protocol` list, which is declared by the registered extractors. The behavior is similar to lavalink. For example, if you need to make youtube search, you can use `ytsearch:QUERY_VALUE`, which will be routed to the extractor that supports this protocol. If no extractor is found, discord-player switches back to old behavior.
Default extractors such as:
- YoutubeExtractor (`ytsearch`, `youtube`)
- SoundcloudExtractor (`scsearch`, `soundcloud`)
- SpotifyExtractor (`spsearch`, `spotify`)
- AppleMusicExtractor (`amsearch`, `applemusic`)
support protocols.

feat(BaseExtractor): add protocols support

---

apps/website/src/data/showcase.ts

I built this bot covering all the major topics of this library such as:
- custom playlists (saving/retrieving tracks from database)
- creating custom extractors to handle custom playlists
- using redis as query cache provider
- persistent player config (saving volume, filters, etc in database)
- web interface to manage the queue via gui *WIP*
- and more...

docs: add music-bot to showcase

---

apps/website/src/data/showcase.ts

Update community bot [Music-Disc](https://github.com/hmes98318/Music-Disc) module version to **v6.6.6**, and Repository link

docs: Update community bot Music-Disc version

---

packages/extractor/src/extractors/common/helper.ts

Fixed an error caused when trying to use tokens with the play-dl library that would cause extraction errors for any song.

Fix play-dl cookie setting error

---

apps/website/src/pages/guide/_guides/hooks/using_hooks.mdx
packages/discord-player/src/hooks/common.ts
packages/discord-player/src/hooks/context/async-context.ts
packages/discord-player/src/hooks/index.ts
packages/discord-player/src/hooks/useHistory.ts
packages/discord-player/src/hooks/useMetadata.ts
packages/discord-player/src/hooks/usePlayer.ts
packages/discord-player/src/hooks/useQueue.ts
packages/discord-player/src/hooks/useTimeline.ts
packages/discord-player/src/hooks/useVolume.ts
packages/discord-player/src/utils/Util.ts

Previous methods still work and this mode is opt-in. In order to enable this api, the command handler needs to provide context to `HooksContextProvider` and hooks must be called without any arguments. The benefit of this approach is you don't need to care about passing guild id every time you want to access something inside the command. Hooks will resolve correct data even if the same command is executed multiple times concurrently.
> Note: This only works inside the call stack created by `withContext` function.
```js
const { withContext } = require('discord-player');
client.on('interactionCreate', async (interaction) => {
if (!interaction.isCommand()) return;
// assuming the following code is your target command to be executed
const command = getCommandSomehow(); // shape is roughly { …
```

feat: add async context api for hooks

---

packages/discord-player/src/utils/QueryResolver.ts

This PR will close #1891.
As pointed out on [the comment](https://github.com/Androz2091/discord-player/issues/1891#issuecomment-2012012203), the query resolver rejects `m.youtube.com` domain because it is not in `DomainsMap.YouTube`.
It will be fixed by adding `'m.youtube.com'` to the array.

Now player can search on m.youtube.com (#1891)

---

packages/extractor/src/extractors/YoutubeExtractor.ts

YoutubeExtractor `bridge()` method used `track.url` for searching resulting in no search results (e.g. spotify url provided when using youtube as bridge, then youtube extractor tries searching for spotify track url..).
This PR fixes this bug by creating an actual searchable query string which then gets executed, to finally return a track.

Fix Youtube bridge query issue using url instead of creating string

---

packages/discord-player/src/fabric/Track.ts
packages/extractor/src/extractors/AttachmentExtractor.ts
packages/extractor/src/extractors/YoutubeExtractor.ts

Fixes <Track>.raw being typed RawTrackData and export .live property from .raw

Fix: Type mismatch in the <Track>.raw property

---

packages/discord-player/__test__/Player.spec.ts
packages/discord-player/src/Player.ts
packages/discord-player/src/types/types.ts

Add ffmpegPath option to player instead of setting the path via process.env.FFMPEG_PATH

Add ffmpegPath option

---

README.md
apps/eris-bot/package.json
apps/eris-bot/src/index.ts
apps/website/src/pages/guide/_guides/welcome/welcome.mdx
packages/discord-player/README.md
packages/discord-player/package.json
packages/discord-player/src/Player.ts
packages/discord-player/src/compat/createErisCompat.ts
packages/discord-player/src/index.ts
packages/extractor/package.json
yarn.lock

feat: eris compat mode

---

packages/discord-player/src/queue/GuildQueue.ts
packages/discord-player/src/queue/GuildQueuePlayerNode.ts

+ edited GuildQueuePlayerNode.ts: #throw to emit 'finish' when the queue is empty
+ edited GuildQueue.ts: #performFinish to run even if track is null.
emptyQueue event now triggers correctly after playerError event.

fix: (emptyQueue event) edited throw to emit 'finish' when queue is empty

---

packages/discord-player/src/compat/createOceanicCompat.ts

[7.2.0-dev.0](https://www.npmjs.com/package/discord-player/v/7.2.0-dev.0) was requiring oceanic.js on discord.js bots. I believe this should fix the issue

Change from import * as to import type

---

packages/discord-player/src/utils/QueryResolver.ts

Keep all youtube params from URL. v/index (possibly other param) that needed to play the playlist from given URL index or other purposes.

chore: keep youtube params

---

packages/extractor/src/extractors/SpotifyExtractor.ts

This PR updates the line that fetches the thumbnail from spotifyData specifically for the QueryType.SPOTIFY_SONG case.
As shown in the first screenshot, the previous implementation always returned the same image. The second screenshot shows the corrected line, which now retrieves the proper song thumbnail.
I tested this manually for several hours to ensure the fix works correctly and consistently.

Update SpotifyExtractor.ts Thumbanil Song Fix
