Androz2091/discord-player

README.md

Add new properties and remove example to the README

Add Song.requestedBy usage and remove example

---

src/Song.js

Sometimes an extra zero counts 😉

Fix song duration

---

package.json
src/Player.js

Similar changes to my PR to master.
The Soundcloud Client ID is specified in the options parameter to Player.

feat: play soundcloud tracks

---

src/Track.js

Bring back support for Node.js v12

---

src/Player.js

set highWaterMark

---

package.json
src/Track.js

Basicly added if statements to choose if added track is comming from playlist or not.
Tracks from playlists have channel property, in non playlist tracks same property is called author.

:bug: Fixed author and duration undefined errors

---

src/Player.js

Fix soundcloud.getSongInfo is not a function

Fix soundcloud.getSongInfo is not a function

---

README.md

Another small PR to update the examples present in the README to be consistent with the current versions definitions.
Let me know if you need any edits to be made :)

Updated readme with current version definitions

---

src/Player.js

Sometimes it is useful to play stereo as mono.

:sparkles: Added mono output

---

src/Player.js

Displays an error and tries to play the music.

:bug: Return after emitting error event

---

src/Util.js

:art: Clean up code

---

src/Player.js

Previous changes were reduced to atoms (idk) 😂

:zap: Improve bass, normalizer and 8D filters

---

src/Player.js
typings/index.d.ts

The default value for firstResult is set to false.

:bug: firstResult default false

---

src/Player.js

PR adds:
- `LiveVideo` to Player#error event

chore: add 'LiveVideo' to Player#error

---

src/Player.js
src/Util.js

I tested this on my bot, it's working so far.
Merging this can close #65 and #66.

✨ Support for Spotify playlists and albums

---

src/Player.js

This will allow setting custom filters, e.g.
```
client.player.filters = {
...client.player.filters,
bassboost: "bass=g=5",
vaporwave: "aresample=48000,asetrate=48000*0.9",
reverb: "ladspa=file=tap_reverb:tap_reverb",
};
```

Allow changing and setting custom filters

---

index.js
package.json
src/Player.js
src/Util.js
typings/index.d.ts

- Export everything
- Properly remove xvdl
- Few minor changes in typings
- Bump: ytdl-core & youtube-sr

⚡ properly remove xvdl

---

src/Player.js

✅ fix discord links

---

typings/index.d.ts

I modified the missing type and optional.

Add FiltersOption type and make some types optional

---

README.md

Due to the new update in `youtube-sr` package, Minimum node version required is 14x
Some people didn't notice this and received errors.
Example Issue - #296

📝  Specify Node version in README

---

src/Queue.js
typings/index.d.ts

- Added missing documentation for few Queue getters
- Added missing TypeScript types for `Queue#totalTime` and `PlayerError`
closes #305 and closes #309

add missing types & docs

---

src/Player.ts
src/types/types.ts

Just a few customizations on the progress bar
- [ X ] These changes have been tested and formatted properly.

New createProgressBar options!

---

src/Player.ts

Utilizing map which results in a much faster spotify playlist/album loading
Removed the current for loop, and changed it to a map which greatly enhances loading times when it comes to spotify playlists and albums.

Fixed spotify album/playlist loading

---

package.json
yarn.lock

chore(deps): bump ytdl-core

---

package.json
src/Player.ts

revert extractor first

---

src/Structures/Queue.ts

Added "trackEnd" event

---

README.md

:pencil: Remove useless import in readme v5

---

CONTRIBUTING.md
docs/migrating/migrating.md
src/Player.ts

Found a few typo's when browsing trough the repo, fixed the ones i found.
No breaking changes

docs: fix typo

---

src/Structures/Queue.ts

fix(Queue): fix jump

---

README.md

message is not defined in this situation, that's why interaction must be used instead
- [ X] These changes have been tested and formatted properly.
- [X ] This PR includes only documentation changes, no code change.

fix(example): message is not defined

---

example/music-bot/index.js

fix(example): fix resume message

---

src/VoiceInterface/StreamDispatcher.ts

Handle the error produced when trying to destroy the connection after you manually disconnect the bot from the voice channel

fix: connection destroy error

---

README.md

This pr adds [Musico](https://github.com/Whirl21/Musico) as an example of bots made by the community 
There is only 1 updated bot using version 13
- [ ✔️ ] These changes have been tested and formatted properly.
- [ ✔️ ] This PR includes only documentation changes, no code change.
- [ ❌ ] This PR introduces some Breaking changes.

🎵 add musico as an example

---

README.md

Added [Eyesense-Music-Bot](https://github.com/naseif/Eyesense-Music-Bot) as an example in the README
- [✅] These changes have been tested and formatted properly.
- [✅] This PR includes only documentation changes, no code change.
- [❌] This PR introduces some Breaking changes.

Added Eyesense-Music-Bot as an example!

---

src/Structures/Track.ts

Added playlist in track Object
- [* ] These changes have been tested and formatted properly.
- [* ] This PR includes only documentation changes, no code change.

docs(Track): add missing playlist property

---

README.md
docs/extractors/create_stream.md
example/music-bot/index.js
example/music-bot/package.json
package.json
src/Player.ts
src/Structures/Queue.ts
src/Structures/Track.ts
src/VolumeTransformer.ts
src/smoothVolume.ts
src/types/types.ts
yarn.lock

This update adds support for smooth volume transition
To enable this feature, the following line should be added at the **top** of the **main file**.
This update is now available on `dev` channel: `npm i discord-player@dev`
```js
// CJS
require("discord-player/smoothVolume");
// ESM
import "discord-player/smoothVolume"
```

feat: smooth volume transition

---

src/Player.ts

Fixed typings for getQueue

---

README.md

Adds Melody as an example bot using discord-player, as it utilises the discord-player base package, as well as the downloader and extractor packages, and uses a lot of the features from these packages. This means that it's a good place to refer to if people wanted a reference for making their own music bot.

Add Melody to readme as an example bot

---

src/Player.ts

Fixed the bug that would not allow users to handle adding Spotify playlists and albums to the queue. I may be wrong with deleting "as User" on line 446. 
#1449

⚓ TypeError: Cannot read properties of undefined (reading 'items') (#1449)

---

.github/workflows/docs-deploy.yml
.github/workflows/eslint.yml
.github/workflows/npm-publish-test.yml
.github/workflows/npm-publish.yml
.gitignore
package.json
packages/discord-player/src/Player.ts
packages/discord-player/src/Structures/Queue.ts
packages/discord-player/src/VoiceInterface/StreamDispatcher.ts
packages/downloader/src/Downloader.ts
packages/extractor/src/types/spotify.d.ts

fix(StreamDispatcher): make paused property a getter

---

README.md

Make https://github.com/Androz2091/discord-music-bot outdated

docs: update music bot status

---

packages/discord-player/src/Structures/GuildQueuePlayerNode.ts

fix(GuildQueuePlayerNode): patch seek method

---

packages/discord-player/src/Structures/GuildQueuePlayerNode.ts

fix(GuildQueuePlayerNode): fix stream error

---

docs/migrating/migrating.md

Add `interaction.guild` for player.nodes.create

---

packages/extractor/src/extractors/LyricsExtractor.ts

Added the fullTitle property to the LyricsExtractor

Add fullTitle property to LyricsExtractor

---

docs/community/community_resources.md

Add Beat-Bot to community bots

---

docs/community/community_resources.md

Update the **discord-player** version for the community bot [Music-disc](https://github.com/hmes98318/Music-Disc)

Update community bot Music-disc module version

---

docs/community/community_resources.md

Added DumBot to the music bot list within the community resources in docs.

added link to DumBot within community resources

---

README.md
apps/website/components/pages/Home/Installation.tsx
apps/website/pages/docs/guides/common-errors.md
apps/website/pages/docs/guides/migrating.md
apps/website/pages/docs/guides/welcome.md
docs/faq/common_errors.md
docs/migrating/migrating.md
packages/adapter-local/README.md
packages/adapter-remote/README.md
packages/core/README.md
packages/discord-player/README.md
packages/equalizer/README.md
packages/utils/README.md
packages/voice/README.md
scripts/bootstrap.js

This PR changes `npm install` related commands to `yarn` since npm cache is very problematic for many users who depend on this project.

docs: use yarn in installation examples

---

packages/discord-player/src/extractors/BaseExtractor.ts
packages/discord-player/src/extractors/ExtractorExecutionContext.ts
packages/extractor/src/extractors/AppleMusicExtractor.ts
packages/extractor/src/extractors/SpotifyExtractor.ts
packages/extractor/src/extractors/YoutubeExtractor.ts

This update adds initialization options to some extractors and also adds intellisense for `register` method.

feat(ExtractorExecutionContext): infer ext initialization options

---

packages/discord-player/src/Player.ts

fix(Player): set query cache properly

---

docs/community/community_resources.md

Updated the version of `Mittelbot` to the latest version

[DOCS-FIX] Update version of community bot

---

docs/community/community_resources.md

Update version used in Botanique

docs: update version botanique

---

docs/community/community_resources.md

- Add my bot(그린Bot) in community resources. This is korean bot so maybe korean developer can get information about this module.
- Bots are sorted by versions.

📝 Add my bot in community resoureces, and Sort by versions.

---

docs/community/community_resources.md

Update community bot [Music-Disc](https://github.com/hmes98318/Music-Disc) module version to v6.3.0, and Sort by versions.

Update community bot Music-Disc version

---

docs/community/community_resources.md

Added my bot

---

docs/community/community_resources.md

Update my community bot version and description

---

apps/website/pages/docs/guides/community-resources.md
docs/community/community_resources.md

This PR adds [mirasaki-music-bot](https://github.com/Mirasaki/mirasaki-music-bot) to the list of Community Resources
I wasn't sure which of the 2 markdown files to edit 🥺

docs(resources): add Mirasaki Music Bot

---

docs/community/community_resources.md

그린Bot URL changed (github.com/GreenScreen410/GreenBot)

📝 Fix broken URL in document

---

apps/website/src/data/showcase.ts

I have bumped discord-player's version to 6.6.0 recently so I would like to update the website's version

docs(resource): update flowease's discord-player version in showcase.ts

---

apps/website/src/data/showcase.ts

Added a new entry to the showcase for a bot I created.

Add showcase

---

apps/website/src/data/showcase.ts

docs(resource): update 'auricle-music-bot' description

---

apps/website/src/data/showcase.ts

added yandexmusic extractor to showcase

Update showcase.ts (added yandexmusic ext)

---

apps/website/src/data/showcase.ts

Update showcase version number for Cadence from `6.6.2` to `6.6.3`.

Update showcase version number for Cadence

---

apps/website/src/data/showcase.ts

Version bump from `6.2.1` to `6.6.3` and description update

docs: Update showcase of Botanique

---

apps/website/src/data/showcase.ts

- just the showcase version to the latest 
- Improved the description of the bot

docs: update Mittelbot showcase version & description

---

apps/website/src/data/showcase.ts

Update Cadence bot `discord-player` version number to 6.6.4.

Update Cadence discord-player version

---

apps/website/src/data/showcase.ts

Version bump from `6.6.3` to `6.6.4`

bump version of botanique

---

packages/extractor/src/extractors/common/helper.ts

fix(helper): fix play-dl setToken

---

apps/website/src/data/showcase.ts

Add my Elite Music bot to the showcase section on the website.

docs(resource): add Elite Music bot to the showcase

---

packages/discord-player/__test__/QueryResolver.spec.ts
packages/discord-player/src/Player.ts
packages/discord-player/src/utils/QueryResolver.ts

fix(QueryResolver): follow known redirect uri

---

packages/discord-player/src/manager/GuildNodeManager.ts
packages/discord-player/src/manager/GuildQueue.ts
packages/discord-player/src/manager/GuildQueueHistory.ts
packages/discord-player/src/manager/GuildQueuePlayerNode.ts

feat(GuildQueue): add track skip reason, remove skipOnNoStream

---

apps/website/src/data/showcase.ts

Updated bhop music bot's version

update bhop music bot's version

---

packages/discord-player/__test__/QueryResolver.spec.ts
packages/discord-player/src/utils/QueryResolver.ts

fix(QueryResolver): update apple music playlist regex

---

packages/discord-player/src/Player.ts
packages/discord-player/src/types/types.ts
packages/extractor/src/extractors/AttachmentExtractor.ts

fix(AttachmentExtractor): set probe timeout

---

packages/extractor/src/extractors/common/BridgeProvider.ts

Fixes demuxer optimization for yt bridged tracks.

fix(BridgeProvider): add demuxer support

---

packages/discord-player/src/Player.ts

Enable demuxer optimization by default.

fix(Player): enable demuxer optimization by default

---

apps/website/src/pages/guide/_guides/youtube/ip_rotation.mdx

Mark `@distube/ytdl-core` as supported lib.

docs: update ip rotation guide page

---

packages/extractor/src/extractors/index.ts

Exports `BridgedExtractor` from the extractor module (#1837)

export `BridgedExtractor`

---

packages/discord-player/src/Player.ts
packages/discord-player/src/manager/GuildQueue.ts
packages/discord-player/src/utils/PlayerEventsEmitter.ts

This PR reduces computations needed to prepare each debug logs.

perf: optimize debug logs

---

apps/music-bot/src/commands/play.ts
packages/discord-player/package.json
packages/discord-player/src/manager/GuildQueue.ts
packages/discord-player/src/utils/QueryResolver.ts
packages/extractor/package.json
packages/extractor/src/extractors/YoutubeExtractor.ts
yarn.lock

This PR adds youtube mixes support in discord-player.

feat(YoutubeExtractor): add mixes support

---

packages/discord-player/src/extractors/BaseExtractor.ts
packages/discord-player/src/extractors/ExtractorExecutionContext.ts
packages/extractor/src/extractors/AttachmentExtractor.ts

Priority defines which extractors are executed first.

feat(BaseExtractor): add priority

---

apps/website/src/pages/guide/[topic]/[page].tsx
apps/website/src/pages/guide/_guides/faq/serialization_and_deserialization.mdx

Document serialization and deserialization process.

docs: add serialization and deserializaiton guide

---

.github/FUNDING.yml

Patreon links cannot be multiple it seems, so I had to replace it.

chore: update FUNDING

---

packages/extractor/src/extractors/AppleMusicExtractor.ts
packages/extractor/src/extractors/SpotifyExtractor.ts

Fixed the build failure introduced in previous PR

fix: handle eslint failure

---

apps/website/src/pages/guide/_guides/extractors/creating_extractor.mdx

docs: add protocol example in guide

---

apps/website/src/pages/showcase.tsx

Added the debounce feature so that the search functionality works with a debounce (_really necessary when making API calls_).
Also cleaned the UI a little bit

feat: added debounced to search and cleaned the UI

---

apps/website/src/components/footer/index.tsx

fix: responsive footer

---

apps/website/src/data/showcase.ts

[Showcase] Updated Jappan discord-player version

Update showcase - Jappan version

---

apps/website/src/data/showcase.ts

added my bot [muusik.app](https://muusik.app)

feat: add muusik.app

---

apps/website/src/lib/docs.ts

- Docs : Updated all links from old discord.js docs to new one

Docs : Update links from old discord.js docs to new one

---

packages/extractor/src/extractors/common/helper.ts

Implement cookie header option for the yt-stream YouTube engine

Implement yt-stream cookie

---

apps/website/src/data/showcase.ts

added discord-player-tidal extractor to showcase

---

apps/website/src/data/showcase.ts

Showcase - Updated the version used in Elite Music to the latest v6.6.8

Update showcase for Elite Music

---

packages/discord-player/package.json
packages/discord-player/src/utils/Util.ts

Fix: update @web-scrobbler/metadata-filter to deps

---

apps/website/src/data/showcase.ts

Update description & version for discord-player-bot in showcase

---

package.json
packages/discord-player/__test__/QueryResolver.spec.ts
packages/discord-player/src/utils/QueryResolver.ts

Add soundcloud mobile regex to the list of `preResolve` URLs

Add soundcloud regex

---

apps/website/src/data/showcase.ts

Adding WD-40
- [ X] These changes have been tested and formatted properly.

Added WD-40 to showcase.ts

---

apps/website/src/data/showcase.ts

Updated link to DumBot in the showcase, also updated the version

updated dumbot link and version

---

apps/website/lib/data/showcase.ts

- [x ] These changes have been tested and formatted properly.
- [x ] This PR includes only documentation changes, no code change.

Addes soundgasm ext

---

packages/discord-player/src/Player.ts

fix(Player): handle null metadata

---

apps/website/lib/data/showcase.ts

- [ x] These changes have been tested and formatted properly.
- [x ] This PR includes only documentation changes, no code change.

add tts ext

---

packages/discord-player/src/compat/createOceanicCompat.ts

I feel bad making a third pull request but this should be it, its should fully working this time. (Changing import * to import type broke and i didn't realize it would break anything). Its much easier for me to test after you release a dev build so i'm sorry
The Soundcloud extractor isn't working right for me so its hard to test this.

Oceanic bug fix

---

apps/website/lib/data/showcase.ts

Bumped my bot's (elite music) discord-player version to the latest after recent update.

docs: bump elite music version

---

apps/website/lib/data/showcase.ts

I renamed 2 extractors, so i changed their links
Also added Soundcloud, Spotify and Apple music reworked extractors

Changed urls and added extractors

---

apps/website/lib/data/showcase.ts

docs(resource): update 'auricle-music-bot' version

---

packages/discord-player/src/Player.ts
packages/discord-player/src/fabric/SearchResult.ts
packages/discord-player/src/queue/GuildQueuePlayerNode.ts
packages/discord-player/src/utils/FFmpegStream.ts
packages/extractor/src/extractors/AttachmentExtractor.ts
packages/extractor/src/extractors/SpotifyExtractor.ts

Initial Issue: RequestOptions (containing custom User-Agent and authentication headers) were working during the search phase but not being applied during FFmpeg streaming, resulting in the default "Lavf/59.27.100" User-Agent instead of custom headers.
1. AttachmentExtractor.ts - RequestOptions Storage
2. Player.ts - RequestOptions Persistence
3. GuildQueuePlayerNode.ts - RequestOptions Retrieval
4. FFmpegStream.ts - FFmpeg Argument Formatting
+ Bonus: In SpotiftyExtractor - spotifyData.visualIdentity field does not exists due to not being in SpotifySong type, so I made it use the coverArt field instead. Couldn't compile without this change, no idea why it's there in the first place, maybe I don't get it.
<sub><sup>Didn't want to create a separte PR for this small issue... Please spare …

Fix ffmpeg request options

---

apps/website/lib/data/showcase.ts

Added information about a new [discord-player-vkmusic](https://www.npmjs.com/package/discord-player-vkmusic) extractor to the extractors documentation page.  
This extractor allows searching and playing tracks from VK Music.

docs(extractors): add vkmusic extractor
